# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmt2iABDunBLiVOBrwsnzZFgE3oYurbY
"""

import random
import string

# المستخدم يحدد الطول
length = int(input("ادخل طول كلمة السر: "))

# اختيار نوع الباسورد
print("اختار نوع كلمة السر:")
print("1 - حروف فقط")
print("2 - حروف + ارقام")
print("3 - حروف + ارقام + رموز")

choice = input("اختيارك: ")

if choice == "1":
    characters = string.ascii_letters
elif choice == "2":
    characters = string.ascii_letters + string.digits
elif choice == "3":
    characters = string.ascii_letters + string.digits + string.punctuation
else:
    print("اختيار غلط")
    characters = string.ascii_letters

# توليد الباسورد
password = ''.join(random.choice(characters) for i in range(length))

print("🔐 كلمة السر:", password)
again = input("تحب تعمل باسورد تاني؟ (y/n): ")
if again == "y":
    print("شغل الكود تاني")